function cf_writetable(obj)
%
%-------function help------------------------------------------------------
% NAME
%   cf_writetable.m
% PURPOSE
%   write GrossProps and Transgression tables to a file
% USAGE
%   cf_writetable(obj)
% INPUTS
%   obj - instance of CF_TransModel class
% OUTPUT
%   ouput tables written to a text or spreadsheet file
% SEE ALSO
%   called in ChannelForm to write tables generated by CF_ChannelForm and
%   CF_TransModel
%
% Author: Ian Townend
% CoastalSEA (c) Jan 2022
%--------------------------------------------------------------------------
%
    gpdst = obj.Data.GrossProps.DataTable;
    if isfield(obj.Data,'Transgression')
        trdst = obj.Data.Transgression.DataTable;
        gpdst = horzcat(gpdst,trdst);
    end
    promptxt = {'File name','File type (text or spreadsheet)'};
    answer = inputdlg(promptxt,'Write table',1,{'table','spreadsheet'});
    if isempty(answer), return; end
    filename = answer{1};
    filetype = answer{2};
    
    writetable(gpdst,filename,'FileType',filetype,'WriteRowNames',true)
    getdialog('Table written to file');
end